### ISSUE TITLE
get back to it?

### ISSUE THREAD

**Issue by aschetti** [aschetti/ReproHack2019Leiden#1]
Hi @eirini-zormpa,
happy new year! I hope you had nice and relaxing holidays!
Following our plan during ReproHack 2019, I was wondering if you were still interested in providing feedback to the authors of the paper we attempted to reproduce. Let me know!

**Comment by eirini-zormpa** [comment]
Happy new year! Yes, let's do it! Shall we continue working on the Rmd and share with the authors? Or were you thinking of something else?

**Comment by aschetti** [comment]
I would just follow our initial plan: write a _.Rmd_ with our comments, provide some simple solutions, and share the final document with them.
When would you have time to work on this?

**Comment by eirini-zormpa** [comment]
sounds good! I should be able to work on it on Thursday and Sunday. We probably don't need too much still I think!

**Comment by aschetti** [comment]
True, we've already done quite a lot. I will be travelling this week so I won't be able to contribute, but if you manage to work on it and let me know when you're done (i.e., with a message here) I can take over asap!

**Comment by eirini-zormpa** [comment]
sounds good! Enjoy your trip :)

**Comment by aschetti** [comment]
Thanks! It will be a work trip, but I'll do my best to enjoy nonetheless :grin:

**Comment by eirini-zormpa** [comment]
hey! couldn't work on it this weekend after all, but had some time today :)
Let me know if you'd like me to look at anything again!

**Comment by aschetti** [comment]
Hi Eirini,
I have worked on this a bit more. I reorganized the folders and created (what I hope is) a clearer structure for our report (_ReproHack2019Leiden.Rmd_). When you have time, would it be possible for you to continue from where I left (i.e., until the `OLD COMMENTS` section)?

Thanks!

**Comment by aschetti** [comment]
I have now completed our attempts at reproducing the preregistered and exploratory results. It would be very helpful if you could go through the document and clean up the comments, to make them more readable and digestible. Thanks!

**Comment by eirini-zormpa** [comment]
hey! yes will do, I was moving the last few days so had zero time. I'll try to take a look tonight or tomorrow evening, hope that's okay :)

**Comment by aschetti** [comment]
No problem, there is no rush at all! I hope your moving went smoothly... I know how stressful it can be!
